version: '3.6'
services:
  app:
    build: .
    container_name: ruby-web-app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec pumactl start"
    volumes:
      - .:/rubywebapp
      - public-data:/rubywebapp/public
      - tmp-data:/rubywebapp/tmp
      - log-data:/rubywebapp/log
    depends_on:
      - postgres
  postgres:
    image: postgres:11-alpine
    container_name: postgres-db
    volumes:
      - ./db-data:/var/lib/postgresql/data
    hostname: ruby-web-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
  pgadmin4:
    image: dpage/pgadmin4:5.6
    container_name: ruby-web-pgadmin4
    ports:
      - 10000:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    depends_on:
      - postgres
    restart: always
  web:
    build: nginx-build
    container_name: ruby-web-nginx
    volumes:
      - public-data:/rubywebapp/public
      - tmp-data:/rubywebapp/tmp
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
    public-data:
    tmp-data:
    log-data:
    db-data:
